### ISSUE TITLE
[BUG] 使用这个插件以后本地的postfix就会1个变成2个一样的。

### ISSUE THREAD

**Issue by StackTc** [docer-savior/docer-savior-idea-plugin#43]
<img width="700" alt="image" src="https://user-images.githubusercontent.com/22773866/173723696-31b0003f-8dd8-422a-ae0e-14b2c9e5e049.png">

**Comment by gudqs7** [comment]
还真是..... 让人懵逼.....
咋回事啊... 我再看看

**Comment by gudqs7** [comment]
大概知道了... 很快搞定
