### ISSUE TITLE
最新安装的2.0.5版本有乱码哦

### ISSUE THREAD

**Issue by robert-fandom** [docer-savior/docer-savior-idea-plugin#6]

**Comment by gudqs7** [comment]
@robert-fandom 麻烦描述具体一些, 是哪块有乱码?

**Comment by chzcb** [comment]
![image](https://user-images.githubusercontent.com/5868472/168192517-cb78cf4c-61a7-494c-be32-1f4bc4c667ec.png)
2.0.6 也有乱码. 有朋友拉代码本地重新编码替换jar就恢复了, 不过我依旧不行. 2.0.4 升级后出现

**Comment by chzcb** [comment]
找到问题了, 和IDEA的默认JVM编码 有关系, 2.0.4 生成的时候应该选择编码了吧?
 升级到2.0.5和2.0.6之后, 乱码解决方案就是在 IDEA的VM参数里面添加 -Dfile.encoding=UTF-8

**Comment by gudqs7** [comment]
@chzcb (⊙o⊙)…    我这边测试了一下修改接口代码的文件编码, gbk 也是没问题的, 你这边的代码是在jar包里面吗?
![image](https://user-images.githubusercontent.com/25474608/168258949-e3343361-ee96-460a-8a7a-1543ae5faa8c.png)

**Comment by gudqs7** [comment]
@chzcb ok

**Comment by gudqs7** [comment]
找到原因了, 是因为添加了如下代码
```java
public static String renderTemplate(String templateName, Map<String, Object> root) {
        try {
            Configuration cfg = new Configuration(Configuration.VERSION_2_3_22);
            cfg.setClassLoaderForTemplateLoading(FreeMarkerUtil.class.getClassLoader(), "template/ftl");
            cfg.setDefaultEncoding("UTF-8");
            cfg.setTemplateExceptionHandler(TemplateExceptionHandler.RETHROW_HANDLER);

            Template temp = cfg.getTemplate(templateName);
            ByteArrayOutputStream arrayOutputStream = new ByteArrayOutputStream(4096);
            Writer out = new OutputStreamWriter(arrayOutputStream);
            temp.process(root, out);
            byte[] bytes = arrayOutputStream.toByteArray();
            return new String(bytes, StandardCharsets.UTF_8);
        } catch (Exception e) {
            ActionUtil.handleException(e);
        }
        return null;
    }
```

这段是用 FreeMarker 来渲染的过程, 问题出在这行 `            return new String(bytes, StandardCharsets.UTF_8);`

这里直接使用了 `UTF-8` , 是错的写法, 因为里面的 root 里面的数据的编码是根据 `-Dfile.encoding` 来的, 默认情况下, Windows 是 `GBK` , 我自己开发调试一直加了 `-Dfile.encoding=UTF-8`, 所以一直没发现, 解决方式就是获取实际的 `-Dfile.encoding` 来替换 `UTF-8` ; 不过其实这个过程 `String` 的构造方法就有帮忙实现: 
```java
Charset cs = Charset.defaultCharset();

String csn = GetPropertyAction
                        .privilegedGetProperty("file.encoding");
```

**Comment by chzcb** [comment]
赞啊, 编码这块在日常开发中是挺麻烦的.
我之前的做法都是全部统一成UTF-8, 输入的编码获取内容后, 先转成UTF-8, 这样使用和输出就统一了.

**Comment by gudqs7** [comment]
Fixed in Release v2.0.8
