### ISSUE TITLE
[Feature] 建议删除随机的中文填充，或者加个设置关闭它

### ISSUE THREAD

**Issue by lorna1** [docer-savior/docer-savior-idea-plugin#79]
建议删除随机的中文填充，或者加个设置关闭它，看上去文档像乱码

**Comment by gudqs7** [comment]
![image](https://user-images.githubusercontent.com/25474608/185533314-5ac9935b-3925-4e6f-9203-ae554eefcfde.png)
加 docer-config.properties 文件于项目根目录(其他目录也行), 添加 `default.notUsingRandom=true` 即可
更多设置见枚举: `cn.gudqs7.plugins.common.enums.PluginSettingEnum`

**Comment by ExtremeYu** [comment]
建议还是不要用配置文件，有个协作问题，每个人配置不一样，不小心提交上去覆盖别人配置，还是做一个配置界面好点
